document/components/docs/en-US/action-sheet.md, document/components/docs/zh-CN/action-sheet.md, example/pages/action-sheet.vue
=> update action-sheet demo and doc

document/components/docs/en-US/dialog.md, document/components/docs/en-US/picker.md, document/components/docs/en-US/time-picker.md, document/components/docs/zh-CN/dialog.md, document/components/docs/zh-CN/picker.md, document/components/docs/zh-CN/time-picker.md, example/pages/dialog.vue, example/pages/picker.vue, example/pages/time-picker.vue
=> update timer-picker and picker demo and doc

document/components/docs/zh-CN/picker.md
=> update picker doc

document/components/docs/en-US/quick-start.md, document/components/docs/zh-CN/quick-start.md
=> update quick-start doc

example/index.html, src/common/stylus/base.styl, src/common/stylus/mixin.styl, src/common/stylus/theme/default.styl, src/components/action-sheet/action-sheet.vue, src/components/picker/picker.vue
Updata these two components-- ActionSheet、Picker for iPhone X compatibility.
Add the property padding-bottom for container, the value is `safe-area-inset-bottom` ，compatible for iOS 11.1  constant and iOS 11.2 env
=> iPhone X compatible: ActionSheet、Picker

example/data/index-list.json, example/pages/index-list.vue, src/components/index-list/index-list-group.vue, src/components/index-list/index-list-item.vue, src/components/index-list/index-list.vue, src/modules/index-list/index.js, test/unit/specs/index-list.spec.js
=> Index-list: add item slot + get actual title height and sub title height + add data property shortcut

.github/ISSUE_TEMPLATE.md
=> update: issue-template

document/components/docs/en-US/cascade-picker.md, document/components/docs/en-US/picker.md, document/components/docs/zh-CN/cascade-picker.md, document/components/docs/zh-CN/picker.md, example/pages/picker.vue, src/components/cascade-picker/cascade-picker.vue, src/components/picker/picker.vue, test/unit/specs/cascade-picker.spec.js, test/unit/specs/picker.spec.js
=> Picker alias dev

example/pages/slide.vue, src/components/slide/slide-item.vue, src/components/slide/slide.vue
=> <update>(slide): handle refresh in component

src/components/upload/ajax.js
=> upload bug fix

document/components/docs/en-US/cascade-picker.md, document/components/docs/en-US/picker.md, document/components/docs/en-US/time-picker.md, document/components/docs/zh-CN/cascade-picker.md, document/components/docs/zh-CN/picker.md, document/components/docs/zh-CN/time-picker.md, src/components/cascade-picker/cascade-picker.vue, src/components/picker/picker.vue, src/components/time-picker/time-picker.vue
在文档中没有把props写成连字符格式，因为考虑到API调用时是用驼峰
=> Add: Picker swipeTime

example/pages/picker.vue, src/common/helpers/instantiate-component.js, src/components/picker/picker.vue
=> <add>(create-api): $updateProps + (picker): watch selectedIndex

src/common/mixins/picker.js, src/components/cascade-picker/cascade-picker.vue, src/components/picker/picker.vue
=> <add>: pickerMixin

document/components/docs/en-US/index-list.md, document/components/docs/zh-CN/index-list.md, src/components/index-list/index-list.vue, test/unit/specs/index-list.spec.js
=> feat(Index list): navbar prop

example/App.vue, src/common/helpers/dom.js, src/components/index-list/index-list.vue
=> using indexList update homepage

document/components/docs/en-US/index-list.md, document/components/docs/en-US/scroll.md, document/components/docs/zh-CN/index-list.md, document/components/docs/zh-CN/scroll.md, example/pages/index-list/index.vue, example/pages/index-list/pull-down-refresh.vue, example/pages/index-list/pull-up-load.vue, example/pages/scroll.vue, example/router/routes.js, src/components/index-list/index-list.vue, src/components/scroll/scroll.vue, test/unit/specs/index-list.spec.js
=> feat(index-list): pull up load + pull down refresh

src/components/scroll/scroll.vue, test/unit/specs/scroll.spec.js
=> feat(scroll): resetPullUpTxt

example/pages/cascade-picker.vue, src/components/cascade-picker/cascade-picker.vue, src/components/picker/picker.vue, test/unit/specs/cascade-picker.spec.js
=> [feat] cascade-picker: async

example/pages/input.vue, src/components/input/input.vue
update relative to [#178](https://github.com/didi/cube-ui/issues/178)
=> Feat input reverse

document/components/docs/en-US/time-picker.md, document/components/docs/zh-CN/time-picker.md, example/pages/time-picker.vue, src/common/lang/date.js, src/common/mixins/basic-picker.js, src/components/time-picker/time-picker.vue, test/unit/specs/time-picker.spec.js
=> [update] time-picker

build/build.js, build/webpack.modules.conf.js, build/webpack.prod.conf.js, example/pages/time-picker.vue, src/common/helpers/debug.js, src/components/time-picker/time-picker.vue, src/modules/cascade-picker/api.js, src/modules/date-picker/api.js, src/modules/picker/api.js, src/modules/segment-picker/api.js, src/modules/time-picker/api.js
=> [workflow] warn and tip

document/components/docs/en-US/scroll.md, document/components/docs/en-US/slide.md, document/components/docs/zh-CN/scroll.md, document/components/docs/zh-CN/slide.md, example/pages/scroll.vue, example/pages/slide/horizontal.vue, example/pages/slide/vertical.vue, package-lock.json, package.json, src/common/lang/string.js, src/common/mixins/scroll.js, src/components/index-list/index-list.vue, src/components/scroll/scroll.vue, src/components/slide/slide.vue, test/unit/specs/scroll.spec.js, test/unit/specs/slide.spec.js
=> [feat]: scroll + slide

document/components/docs/en-US/toast.md, document/components/docs/zh-CN/toast.md, example/pages/toast.vue
- update Toast document
- update Toast Example
=> Document Toast

package-lock.json, package.json
=> Commit messages

src/components/date-picker/date-picker.vue
=> Optimize DatePicker

document/components/docs/en-US/index-list.md, document/components/docs/zh-CN/index-list.md, example/pages/index-list/pull-down-refresh.vue, example/pages/index-list/pull-up-load.vue, package-lock.json, package.json, src/common/mixins/deprecated.js, src/components/index-list/index-list.vue, src/components/scroll/scroll.vue, src/components/slide/slide.vue
add props "options" for indexList component
closed [#230](https://github.com/didi/cube-ui/issues/230)
=> Feat index list options

document/components/docs/en-US/textarea.md, document/components/docs/zh-CN/textarea.md, example/pages/textarea.vue, src/components/textarea/textarea.vue, test/unit/specs/textarea.spec.js
=> Enhance textarea

document/components/docs/en-US/scroll.md, document/components/docs/zh-CN/scroll.md, example/pages/scroll/config.vue, example/pages/scroll/default.vue, example/pages/scroll/horizontal.vue, example/pages/scroll/index.vue, example/pages/scroll/jd.vue, example/pages/scroll/toutiao.vue, example/router/routes.js
=> docs(scroll): sync examples

document/components/docs/en-US/date-picker.md, document/components/docs/en-US/time-picker.md, document/components/docs/zh-CN/date-picker.md, document/components/docs/zh-CN/time-picker.md, example/pages/time-picker.vue, src/common/lang/date.js, src/components/time-picker/time-picker.vue, test/unit/specs/time-picker.spec.js
=> feat(time-picker): format

document/components/docs/zh-CN/time-picker.md, example/pages/time-picker.vue, src/components/time-picker/time-picker.vue, test/unit/specs/time-picker.spec.js
=> feat(time-picker): support minuteStep rule

document/components/docs/en-US/scroll.md, document/components/docs/zh-CN/scroll.md, example/pages/scroll/jd.vue, example/pages/scroll/toutiao.vue
=> Update scroll docs

document/components/docs/en-US/toast.md, document/components/docs/zh-CN/toast.md, example/pages/toast.vue, src/components/toast/toast.vue, test/unit/specs/toast.spec.js
=> Feat toast no icon

document/components/docs/en-US/input.md, document/components/docs/zh-CN/input.md, example/pages/input.vue, src/components/input/input.vue, test/unit/specs/input.spec.js
=> Feat new input

document/components/docs/en-US/upload.md, document/components/docs/zh-CN/upload.md, src/components/upload/ajax.js, src/components/upload/btn-mixin.js, src/components/upload/btn.vue, src/components/upload/upload.vue, src/components/upload/util.js, test/unit/specs/upload.spec.js
=> Feat new upload

document/components/docs/en-US/swipe.md, document/components/docs/zh-CN/swipe.md, example/pages/swipe/custom.vue, package.json, src/components/swipe/swipe-item.vue, src/components/swipe/swipe.vue, test/unit/specs/swipe.spec.js
=> Swipe handle own active logic

src/common/stylus/theme/default.styl, src/components/button/button.vue
=> refactor(button): opt button: only outline & disabled need border

document/components/docs/en-US/dialog.md, document/components/docs/zh-CN/dialog.md, example/pages/dialog.vue, package.json, src/components/dialog/dialog.vue, src/modules/dialog/index.js, test/unit/specs/dialog.spec.js
=> Feat dialog prompt

document/components/docs/en-US/checkbox-group.md, document/components/docs/zh-CN/checkbox-group.md, package.json, src/components/checkbox-group/checkbox-group.vue, test/unit/specs/checkbox-group.spec.js
=> Feat checkbox group min max

example/pages/scroll/toutiao.vue
=> chore(scroll): fix example bug

example/pages/scroll/jd.vue, example/pages/scroll/toutiao.vue
=> chore: update scroll example's img

src/components/slide/slide.vue
=> fix(slide): goToPage direction

src/modules/sticky/index.js
=> sticky-ele组件导出错误

src/components/slide/slide-item.vue, src/components/slide/slide.vue
=> fix(Slide): fix maxScrollX/Y caculating error in nested Slide

document/components/docs/en-US/date-picker.md, document/components/docs/zh-CN/date-picker.md, example/pages/date-picker.vue, src/common/mixins/basic-picker.js, src/components/cascade-picker/cascade-picker.vue, src/components/date-picker/date-picker.vue, src/components/picker/picker.vue, test/unit/specs/date-picker.spec.js
add columnOrder prop for date-picker. This prop can be use to set display order of date column
=> Feat date picker display order

src/components/scroll/scroll.vue
when inner element can't scroll
* [*] Make sure you follow DiDi's [contributing guide](https://github.com/didi/cube-ui/blob/master/CONTRIBUTING.md).
* [*] Make sure you are merging your commits to `dev` branch.
* [*] Add some descriptions and refer relative issues for you PR.
=> fix(scroll): nested scroll bug

document/components/docs/en-US/scroll.md, document/components/docs/zh-CN/scroll.md, src/components/scroll/scroll.vue, test/unit/specs/scroll.spec.js
=> Optimise scroll pullup

src/components/index-list/index-list.vue, src/components/scroll/scroll.vue
=> fix: forceUpdate

document/components/docs/zh-CN/checkbox-group.md, document/components/docs/zh-CN/radio.md, example/pages/checkbox-group.vue, example/pages/radio.vue, src/common/mixins/group-col.js, src/components/checkbox-group/checkbox-group.vue, src/components/checkbox/checkbox.vue, src/components/radio/radio-group.vue, src/components/radio/radio.vue
add a col configuration to checkbox
=> feat: add a col configuration to checkbox 

src/components/scroll/scroll.vue
=> fix(scroll): pulldown

src/components/segment-picker/segment-picker.vue, src/components/time-picker/time-picker.vue, test/unit/specs/time-picker.spec.js
fix [issue 614](https://github.com/didi/cube-ui/issues/614)
hidden animation works
=> fix(segment-picker): fix no hidden animation

document/components/docs/zh-CN/index-list.md, document/components/docs/zh-CN/scroll-nav-bar.md, document/components/docs/zh-CN/scroll-nav.md, document/components/docs/zh-CN/scroll.md, document/components/docs/zh-CN/slide.md, src/common/bscroll/constants.js, src/common/helpers/env.js, src/common/helpers/util.js, src/components/picker/picker.vue, src/components/scroll/scroll.vue
fix the scrolling problem in IOS13.4 webview
added default description of better-scroll parameter
[better-scroll #978](https://github.com/ustbhuangyi/better-scroll/issues/978)
=> fix the scrolling problem in iOS13.4

src/components/picker/picker.vue
=> fix a bug that confirm event failure in iOS13.4

src/components/checkbox-group/checkbox-group.vue, src/components/checkbox/checkbox.vue
set the min props in checkboxgroup. And checkboxgroup will add value in checkList when repeatedly click the selected checkbox
=> fix(checkboxgroup): fix a bug when checkboxgroup set the min props

types/cube-ui.d.ts
=> add static $create types

src/components/time-picker/time-picker.vue
fix the bug that now is only displayed on the first date, let now be displayed on the current date
=> fix(time-picker): should only display now on the current date

document/common/js/highlight.js, document/components/docs/en-US/date-picker.md, document/components/docs/zh-CN/date-picker.md, example/components/json-view.vue, src/components/date-picker/date-picker.vue
=> Change the props max default value of date-picker

src/components/toolbar/toolbar-item.vue
=> fix: add import path `.vue` .ext

src/components/date-picker/date-picker.vue
Error will be reported when only introducing date pickers
=> fix(picker): date-picker import cascade-picker

src/common/stylus/mixin.styl, src/components/rate/rate-item.vue
=> fix: stylus-loader6.x build error

document/components/docs/en-US/textarea.md, document/components/docs/zh-CN/textarea.md, example/pages/textarea.vue, src/components/textarea/textarea.vue
=> feat: add named slot for textarea

src/components/slide/slide.vue
=> fix: slide在执行play时候可能为null导致报错
